<?xml version="1.0" encoding="utf-8"?><Database Name="DOSMaps" Class="DOSMapsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PEREGRIN\SQLEXPRESS;Initial Catalog=DOSMaps;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DOSMapsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Continent" Member="Continents">
    <Type Name="Continent">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Continent_Chunk" Member="Chunks" ThisKey="ID" OtherKey="Continent_ID" Type="Chunk" />
    </Type>
  </Table>
  <Table Name="dbo.Conversion" Member="Conversions">
    <Type Name="Conversion">
      <Column Name="Code" Type="System.String" DbType="NChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Part" Member="Parts">
    <Type Name="Part">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Country_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Chunk_ID" Type="System.String" DbType="NChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="PrayerNeed" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PrayerResource" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Chunk_Part" Member="Chunk" ThisKey="Chunk_ID" OtherKey="ID" Type="Chunk" IsForeignKey="true" />
      <Association Name="Country_Part" Member="Country" ThisKey="Country_ID" OtherKey="ID" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PrayersFor" Member="PrayersFors">
    <Type Name="PrayersFor">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FromChunk_ID" Type="System.String" DbType="NChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="ToChunk_ID" Type="System.String" DbType="NChar(4) NOT NULL" CanBeNull="false" />
      <Association Name="Chunk_PrayersFor" Member="Chunk" ThisKey="FromChunk_ID" OtherKey="ID" Type="Chunk" IsForeignKey="true" />
      <Association Name="Chunk_PrayersFor1" Member="Chunk1" ThisKey="ToChunk_ID" OtherKey="ID" Type="Chunk" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Chunk" Member="Chunks">
    <Type Name="Chunk">
      <Column Name="ID" Type="System.String" DbType="NChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LongName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullDescription" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Continent_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PrayerNeed" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PrayerResource" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MultiComplete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Chunk_Part" Member="Parts" ThisKey="ID" OtherKey="Chunk_ID" Type="Part" />
      <Association Name="Chunk_PrayersFor" Member="PrayersFors" ThisKey="ID" OtherKey="FromChunk_ID" Type="PrayersFor" />
      <Association Name="Chunk_PrayersFor1" Member="PrayersFors1" ThisKey="ID" OtherKey="ToChunk_ID" Type="PrayersFor" />
      <Association Name="Chunk_Country" Member="Countries" ThisKey="ID" OtherKey="Chunk_ID" Type="Country" />
      <Association Name="Continent_Chunk" Member="Continent" ThisKey="Continent_ID" OtherKey="ID" Type="Continent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GivenName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Chunk_ID" Type="System.String" DbType="NChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="PrayerNeed" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PrayerResource" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MultiChunk_ID" Type="System.String" DbType="NChar(4)" CanBeNull="true" />
      <Association Name="Country_Part" Member="Parts" ThisKey="ID" OtherKey="Country_ID" Type="Part" />
      <Association Name="Chunk_Country" Member="Chunk" ThisKey="Chunk_ID" OtherKey="ID" Type="Chunk" IsForeignKey="true" />
    </Type>
  </Table>
</Database>